import type { Metadata } from 'next';
import { CartProvider } from '@/components/context/CartContext';
import Navbar from '@/components/Navbar';
import CartSidebar from '@/components/CartSidebar';
import Footer from '@/components/Footer';
import '@/app/globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function ShopLayout({ children }: { children: React.ReactNode }) {
    return (
        <CartProvider>
            <Navbar />
            <CartSidebar />
            <main className="flex-grow">{children}</main>
            <Footer />
        </CartProvider>
    );
}
